const express = require('express');
const router = express.Router();
const wizytaControler = require('../controllers/wizytaController');
router.get('/', wizytaControler.showWizytaList);
router.get('/add', wizytaControler.showAddWizytaForm);
router.get('/details/:wizyId', wizytaControler.showWizytaDetails);
router.get('/edit/:wizyId', wizytaControler.showWizytaEdit);
router.get('/delete/:wizyId', wizytaControler.showWizytaDelete);
router.post('/add', wizytaControler.addWizyta);
router.post('/edit', wizytaControler.updateWizyta);
router.get('/delete/:wizyId', wizytaControler.deleteWizyta);
module.exports = router;